#nuget version is nly changed by  RELEASE TAG
version: 4.3.1-beta-{build}
image: Visual Studio 2022
pull_requests:
  do_not_increment_build_number: false

init:
  - ps: |
      git config --global core.autocrlf input
      $env:CAN_PUBLISH = $true

      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        $ver = $env:APPVEYOR_REPO_TAG_NAME
        if($ver.StartsWith("v") -eq $true) { $ver = $ver.Substring(1) }
        try
        {         
          Update-AppveyorBuild -Version $ver 
          Write-Host "Update-AppveyorBuild Success to change version to TAG: '$env:APPVEYOR_REPO_TAG_NAME'"   -ForegroundColor Green          
        }
        catch
        {
          Write-Host "Update-AppveyorBuild Fail to change version to TAG: '$env:APPVEYOR_REPO_TAG_NAME'"   -ForegroundColor Red
          Write-Host "Exception Error: $PSItem.Exception.Message" -ForegroundColor Red
          $env:CAN_PUBLISH = $false
        }
      }
  - ps: |
      Write-Host "APPVEYOR_BUILD_VERSION='$env:APPVEYOR_BUILD_VERSION'" -ForegroundColor Yellow
      Write-Host "APPVEYOR_REPO_TAG_NAME= '$env:APPVEYOR_REPO_TAG_NAME'" -ForegroundColor Yellow

configuration: Release

skip_commits:
  files:
    - docs/*
    - art/*
    - '**/*.md'    
    - .gitignore
    - .editorconfig
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update changelog.*/

 
build_script:
- cmd: dotnet build OData2Poco.sln -c Release --version-suffix %APPVEYOR_BUILD_VERSION% 

test_script: 
- cmd: dotnet test OData2Poco.Tests/ 
- cmd: dotnet test OData2Poco.CommandLine.Test/

after_test:
- cmd: dotnet pack OData2Poco.CommandLine/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%  
- cmd: dotnet pack OData2Poco.dotnet.o2pgen/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%  
- cmd: dotnet pack OData2PocoLib/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%  

 
artifacts:
- path: .\build\OData2Poco.dotnet.o2pgen*.nupkg
  name: global_tool
- path: .\build\o2pgen.exe
  name: o2p_exe
- path: .\build\OData2Poco.CommandLine.*.nupkg
  name: o2pgen
- path: .\build\OData2Poco.*.nupkg
  name: lib
- path: '.\build\OData2Poco.*.snupkg'
  name: symbol   
deploy:
- provider: GitHub
  auth_token:
     secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
  artifact: /.*(\.|\.s)nupkg|o2p_exe/            
  prerelease: false  
  on:
    APPVEYOR_REPO_TAG: true

- provider: NuGet
  api_key:
    secure: iQ+rv1ItQVEDS1ktlQN5onitltpVJzvUxptmigYiqHzBhgWceVl7jvzZx6ysOXm+
  on:
    APPVEYOR_REPO_TAG: true # Deploy on tag push only.
    branch: master          # Release from master branch only.
    

# myget
- provider: NuGet
  server: https://www.myget.org/F/odata2poco/api/v2/package
  api_key:
    secure: QAHjX2gqddFX2cNhMNqweMTGQ89q++ezKnQvdAcinY5D1rwbj2vkWeFsTykm4koA
  symbol_server: https://www.myget.org/F/odata2poco/api/v2/package
  